/**
 * CSV and JSON writers, with the provenance needed to reproduce a result.
 *
 * Ported from BCA_quarto `src/bca/export.py` (specdoc §4.3, §3.4).
 *
 * The app offers three switches that change the numbers: blank subtraction, the fit model, and
 * the dilution factor. An export that records the numbers but not the switches is
 * unreproducible — six months later nobody can say whether a column came from the cubic or the
 * quadratic. So every writer emits a provenance block first, and the block is part of the
 * contract, not a courtesy.
 *
 * Nothing here touches the network. Downloads reach the user through a Blob and an object URL,
 * which is what lets this app promise that no absorbance leaves the machine that pasted it.
 */

import { modelLabel } from './constants'
import type { CurveFit } from './curve'
import type { DilutionPlan } from './dilution'
import type { Issue } from './errors'
import { fixed } from './format'
import type { SampleResult } from './samples'

const COMMENT = '#'

/**
 * Render a number for a CSV cell. Absent and non-finite values become an empty field.
 *
 * Writing the literal "None" or "NaN" into a numeric column is how a spreadsheet ends up with
 * text where a number should be, and how a column of concentrations silently stops summing.
 */
function cell(value: number | null | undefined, digits = 4): string {
  if (value === null || value === undefined) return ''
  if (!Number.isFinite(value)) return ''
  return fixed(value, digits)
}

/** Semicolon-joined issue codes for the trailing `issues` column. */
function codes(issues: readonly Issue[]): string {
  return issues.map((i) => i.code).join('; ')
}

/** One CSV field, quoted minimally — only when the content would otherwise break the row. */
function csvField(value: string | number | null | undefined): string {
  const text = value === null || value === undefined ? '' : String(value)
  if (/["\r\n,]/.test(text)) return `"${text.replace(/"/g, '""')}"`
  return text
}

function csvRow(cells: ReadonlyArray<string | number | null | undefined>): string {
  return `${cells.map(csvField).join(',')}\n`
}

/** a, b, c, ... highest power first, matching the coefficient ordering. */
function coefficientNames(count: number): string[] {
  return Array.from({ length: count }, (_, i) => String.fromCharCode(97 + i))
}

export interface ProvenanceOptions {
  fit?: CurveFit | null
  dilutionFactor?: number | null
  extra?: Readonly<Record<string, string | number>>
}

/** Comment lines describing the settings that produced an export. */
export function provenanceHeader(options: ProvenanceOptions = {}): string[] {
  const { fit = null, dilutionFactor = null, extra = {} } = options

  const lines = [`${COMMENT} Pierce BCA protein assay — generated by BCA_web`]

  if (fit !== null) {
    lines.push(`${COMMENT} fit model: ${modelLabel(fit.model)} (${fit.model})`)
    lines.push(`${COMMENT} blank subtracted: ${fit.blankSubtracted ? 'yes' : 'no'}`)
    if (fit.blankMeanAbs !== null) {
      lines.push(`${COMMENT} blank mean absorbance: ${fixed(fit.blankMeanAbs, 4)}`)
    }
    if (fit.fitted) {
      const names = coefficientNames(fit.coefficients.length)
      const terms = fit.coefficients.map((c, i) => `${names[i] as string}=${c}`).join(', ')
      lines.push(`${COMMENT} coefficients (highest power first): ${terms}`)
      lines.push(`${COMMENT} r_squared: ${cell(fit.rSquared, 6) || 'n/a'}`)
      lines.push(
        `${COMMENT} calibrated absorbance range: ${cell(fit.absMin, 3)} to ` +
          `${cell(fit.absMax, 3)} (corrected)`,
      )
    } else {
      // A failed fit still has to leave an audit trail. "No file was produced" is indis-
      // tinguishable from "nobody ran it"; this says which, and why.
      lines.push(`${COMMENT} curve did not fit; concentrations are unavailable`)
      for (const i of fit.issues) lines.push(`${COMMENT} issue: ${i.code} — ${i.message}`)
    }
  }

  if (dilutionFactor !== null) {
    lines.push(`${COMMENT} sample dilution factor: ${dilutionFactor}`)
  }

  for (const key of Object.keys(extra)) {
    lines.push(`${COMMENT} ${key}: ${String(extra[key])}`)
  }

  return lines
}

function withProvenance(lines: readonly string[], body: string): string {
  return `${lines.join('\n')}\n${body}`
}

/** The pipetting scheme, one row per vial. */
export function dilutionPlanToCsv(plan: DilutionPlan): string {
  const header = provenanceHeader({
    extra: {
      'volume per well (uL)': plan.spec.volumePerWellUL,
      replicates: plan.spec.nReplicates,
      'overage factor': plan.spec.overageFactor,
      'stock (ug/uL)': plan.spec.stockConcUgPerUL,
    },
  })

  let body = csvRow([
    'vial_id',
    'final_conc_ug_per_mL',
    'final_conc_ug_per_uL',
    'source',
    'dilution_factor',
    'volume_from_source_uL',
    'volume_diluent_uL',
    'total_volume_uL',
    'leftover_uL',
    'issues',
  ])
  for (const v of plan.vials) {
    body += csvRow([
      v.vialId,
      cell(v.finalConcUgPerML, 2),
      cell(v.finalConcUgPerUL, 6),
      v.source ?? '',
      cell(v.dilutionFactor, 4),
      cell(v.volumeFromSourceUL, 2),
      cell(v.volumeDiluentUL, 2),
      cell(v.totalVolumeUL, 2),
      cell(v.leftoverUL, 2),
      codes(v.issues),
    ])
  }
  return withProvenance(header, body)
}

/** The standards, their means, and their back-calculated recovery. */
export function curveToCsv(fit: CurveFit): string {
  const header = provenanceHeader({ fit })

  let body = csvRow([
    'tube_id',
    'conc_ug_per_mL',
    'n_replicates',
    'mean_absorbance',
    'corrected_absorbance',
    'fitted_ug_per_mL',
    'recovery_percent',
  ])

  fit.levels.forEach((level, index) => {
    const mean = fit.levelMeans[index] ?? null
    const corrected =
      mean === null ? null : fit.blankSubtracted ? mean - (fit.blankMeanAbs ?? 0) : mean
    const fitted =
      mean === null || !fit.fitted
        ? null
        : fit.coefficients.reduce((acc, c) => acc * (corrected as number) + c, 0)
    body += csvRow([
      level.tubeId ?? '',
      cell(level.concUgPerML, 2),
      level.replicates.filter((r) => r !== null).length,
      cell(mean, 4),
      cell(corrected, 4),
      cell(fitted, 4),
      cell(fit.recoveries[index] ?? null, 2),
    ])
  })

  return withProvenance(header, body)
}

/** One row per analysed unknown. */
export function samplesToCsv(
  results: readonly SampleResult[],
  options: ProvenanceOptions = {},
): string {
  const header = provenanceHeader(options)

  let body = csvRow([
    'sample',
    'n_replicates',
    'mean_absorbance',
    'sd_absorbance',
    'cv_percent',
    'conc_ug_per_mL',
    'conc_ug_per_uL',
    'dilution_factor',
    'extrapolated',
    'issues',
  ])
  for (const r of results) {
    body += csvRow([
      r.name,
      r.n,
      cell(r.meanAbs, 4),
      cell(r.sdAbs, 5),
      cell(r.cvPercent, 2),
      // Full precision, because this column is the one that gets pasted into a figure.
      r.concUgPerML === null || !Number.isFinite(r.concUgPerML) ? '' : String(r.concUgPerML),
      r.concUgPerUL === null || !Number.isFinite(r.concUgPerUL) ? '' : String(r.concUgPerUL),
      r.dilutionFactor,
      r.extrapolated ? 'yes' : 'no',
      codes(r.issues),
    ])
  }
  return withProvenance(header, body)
}

/**
 * Replace non-finite numbers with null, recursively.
 *
 * `JSON.stringify` writes Infinity and NaN as `null` already, but only at the top of a value —
 * it is easier to guarantee the round trip by normalising first than to reason about where it
 * does and does not apply.
 */
function jsonSafe(value: unknown): unknown {
  if (typeof value === 'number') return Number.isFinite(value) ? value : null
  if (Array.isArray(value)) return value.map(jsonSafe)
  if (value !== null && typeof value === 'object') {
    const out: Record<string, unknown> = {}
    for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = jsonSafe(v)
    return out
  }
  return value
}

export interface SessionSnapshot {
  readonly plateText?: string
  readonly fit?: CurveFit | null
  readonly samples?: readonly SampleResult[]
  readonly dilution?: DilutionPlan | null
  readonly dilutionFactor?: number
}

/** The whole session as JSON, for archiving beside the figure it produced. */
export function sessionToJson(session: SessionSnapshot): string {
  return JSON.stringify(
    jsonSafe({
      generatedBy: 'BCA_web',
      generatedAt: new Date().toISOString(),
      ...session,
    }),
    null,
    2,
  )
}
